### ISSUE TITLE
We definitely need some README

### ISSUE THREAD

**Issue by amka** [OlegKuksa/join_csv#1]
Ok, to run this project we need README file, maybe simple UI to work with and tests on error cases because it misses a lot of try/except.

**Comment by OlegKuksa** [comment]
Hi @amka  
I will do it.
When I finish I will left message here.

B/R, Oleg Kuksa

**Comment by amka** [comment]
Feel free to have time till Monday.

**Comment by OlegKuksa** [comment]
Hi @amka 
I have added following:
 - Docker developer environment 
 - Readme.md
 - Simple UI
 - New tests

Now I haven't covered all try/except where it needs and I see several bugs that should be fixed.
I will have some time for join_csv next weekend I wiil cover try/except and fix bugs.

Let me know if you have any questions.

**Comment by OlegKuksa** [comment]
Hi @amka 
I covered try/except and fixed bugs.
B/R, Oleg Kuksa
